server:
  port: 8072

spring:
  main:
    allow-circular-references: true
  application:
    name: netdisc-filesystem
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.95.238:9070
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 2000MB
      # 设置单次请求文件的总大小
      max-request-size: 2000MB
  datasource:
    # 配置数据源
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/my_pan?serverTimezone=Hongkong&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid数据源
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 #Redis数据库索引（默认为0）
    password: WHL123456
    timeout: 1800000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

  cache:
    redis:
      cache-null-values: true #是否缓存null数据，默认是false，可以用来解决缓存穿透
      use-key-prefix: true    #缓存数据key是否使用前缀，默认是true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wen.pojo


# 自定义配置文件

netdisc:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
  file:
    #单位 MB
    max-size: 2000
    show-row: 10

  store:
    root-path: D:/pan/store/
    root-id: 0
    #单位 MB
    max-size: 2000

seata:
  service:
    vgroup-mapping:
      # XXX-seata-service-group
      netdisc-service-filesystem-seata-service-group: default
    grouplist:
      default: localhost:8091
