server:
  port: 8081
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: netdisc-oauth
  cloud:
    sentinel:
      transport:
        #配置 Sentinel dashboard 地址
        dashboard: 127.0.0.1:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#激活sentinel对 Feign支持
feign:
  sentinel:
    enabled: true